name: Angular CI Pipeline

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  test_and_build:
    uses: dixitarite/shared-github-workflows/.github/workflows/reusable_final.yml@main
    with:
      node_version: ${{ vars.NODE_VERSION }}
      coverage_threshold: ${{ vars.COVERAGE_THRESHOLD }}
      project_path: 'Angular-project-devops'
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
