name: Angular CI Pipeline

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  test_and_build:
    uses: dixitarite/Angular-project-devops/.github/workflows/reusable-angular-ci.yml@main
    with:
      node-version: '18'             
      coverage-threshold: 80          
      project-path: '.'              
    secrets: inherit
