name: Deploy Angular App

on:
  push:
    branches:
      - main

jobs:
  deploy-static-app:
    uses: dixitarite/Angular-project-devops/.github/workflows/deploy_to_aws.yml@main
    with:
      app_dist_path: dist
      deploy_target: aws
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      AWS_CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }} 
