name: Deploy Angular App

on:
  push:
    branches:
      - main

jobs:
  deploy-static-app:
    uses: dixitarite/Agular-project-devops/.github/workflows/angular-static-deploy.yml@main
    with:
      app_dist_path: dist/my-angular-app
      deploy_target: azure  # or 'aws'
    secrets:
      AZURE_STATIC_WEB_APPS_API_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
